DROP DATABASE IF EXISTS Banco;
CREATE DATABASE Banco;
CREATE USER IF NOT EXISTS 'Banco'@'localhost' IDENTIFIED BY 'Banco';
CREATE USER IF NOT EXISTS 'Banco'@'%' IDENTIFIED BY 'Banco';
GRANT ALL PRIVILEGES ON Banco.* TO Banco@'localhost';
GRANT ALL PRIVILEGES ON Banco.* TO Banco@'%';
FLUSH PRIVILEGES;